# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  # boot.loader.systemd-boot.enable = true;
  boot.loader.grub = {
    enable = true;
    devices = ["/dev/disk/by-id/ata-Micron_1100_MTFDDAV256TBN_1711166AC81F"];
    efiSupport = true;
    enableCryptodisk = true;
  };
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.mitigateDMAAttacks = true;
  boot.initrd.luks.devices = {
    luks00ssd = {
      device = "/dev/disk/by-uuid/3fcf8cef-09af-46b5-9ec9-f4f2409afb7e";
      allowDiscards = true;
      preLVM = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/mapper/luks00ssd";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXOS_BOOT";
      fsType = "vfat";
    };

  fileSystems."encryptedlvmdatahdd" =
    { device = "/dev/mapper/luks01hdd";
      encrypted = {
        enable = true;
        label = "luks01hdd";
        blkDev = "/dev/disk/by-uuid/3fcf8cef-09af-46b5-9ec9-f4f2409afb7e";
        keyFile = "/mnt-root/.hddkey";
      };
    };


  fileSystems."/home" =
    { device = "/dev/mapper/hdddata-home";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/mapper/hdddata-swap"; }
    ];


  services.xserver.libinput = {
    enable = true;
    dev = "/dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-mouse";
  };

  hardware.opengl.driSupport32Bit = true;
  # services.xserver.videoDrivers = ["nvidia"];
  nix.maxJobs = lib.mkDefault 8;
}
