{ config, pkgs, lib, ... }:

let
  vimrc = ''
    " MOGRIA's GLOBAL NixOS vim config
    " --------------------------------
    " WARNING: this file is generated by nixos-rebuild you can find the
    " nix-expression here: /etc/nixos/vim.nix

    " don't be vi compatible
    set nocompatible
    syntax enable
    set autoindent
    set smartindent
    set tabstop=4
    set softtabstop=4
    set shiftwidth=4
    set expandtab
    set number
    set hlsearch
    set incsearch
    set smartcase
    set wildmenu


    " autocommand FileType nix set tabstop=2 shiftwidth=2
    " au FileType nix set tags^=~/.vim/nix.tags

    if filereadable($HOME."/.vimrc")
      source $HOME/.vimrc
    endif
  '';
  vimpkg = pkgs.vim_configurable.customize {
      name = "vim";
      
      vimrcConfig.customRC = vimrc;

      vimrcConfig.vam.knownPlugins = pkgs.vimPlugins;
      vimrcConfig.vam.pluginDictionaries = [
        { names = [
            "vundle"
            "vim-nix"
          ];
        }
      ];
    };
in {
  environment.systemPackages = [ vimpkg ];
  programs.vim.defaultEditor = true;
}
