# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c90674fc-44ad-4e30-bb88-617e903dc23f";
      fsType = "ext4";
    };

  swapDevices = [ ];

  services.xserver.videoDrivers = [ "nvidiaLegacy390" ]; 
  hardware.nvidia = {
    modesetting.enable = true;
    # optimus_prime = {
      # enable = true;
      # intelBusId = "PCI:0:2:0";
      # nvidiaBusId = "PCI:1:0:0";
    # };
  };

  nix.maxJobs = lib.mkDefault 8;
}
