# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      ./../../hardware/wifi/dlink-dwa-172.nix
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages;
  boot.extraModulePackages =  with pkgs.linuxPackages ; [
    nvidia_x11_legacy390
  ];
  boot.supportedFilesystems = [ "zfs" ];

  hardware.enableRedistributableFirmware = true;
  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [ vaapiIntel libvdpau-va-gl vaapiVdpau intel-ocl ];
    # driSupport32Bit = true;
    # extraPackages32 = with pkgs.driversi686Linux; [ glxinfo vaapiIntel libvdpau-va-gl vaapiVdpau ];
  };
  services.xserver.videoDrivers = [ "nvidiaLegacy390" ]; 

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c90674fc-44ad-4e30-bb88-617e903dc23f";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "datadump/home";
      fsType = "zfs";
    };

  fileSystems."/srv/storage" =
    { device = "datadump/shared";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
}
