# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      ../../hardware/kernel.nix
      ../../hardware/opengl.nix
    ];

      ../../hardware/wifi/dlink-dwa-172.nix
    ];

  boot.extraModulePackages =  with pkgs.linuxPackages ; [
    nvidia_x11_legacy390
  ];

  /* TODO: NIXOS 20.03: ./services/hardware/fancontrol.nix is now available */

  hardware.enableRedistributableFirmware = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.legacy_390;

  # Root SSD
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c90674fc-44ad-4e30-bb88-617e903dc23f";
      fsType = "ext4";
    };


  # ZFS File systems
  # For them to mount automatically on system start the following
  # options need to be set for each zfs device
  #
  #  $ zfs set mountpoint=legacy <pool>/<fs>
  #
  # See https://nixos.wiki/wiki/NixOS_on_ZFS for more info
  boot.supportedFilesystems = [ "zfs" ];
  fileSystems."/home" =
    { device = "datadump/home";
      fsType = "zfs";
    };

  fileSystems."/srv/storage" =
    { device = "datadump/shared";
      fsType = "zfs";
    };

  services.zfs = {
    autoScrub.enable = true;
    autoSnapshot.enable = true;
    # no zfs trim needed as the zfs filesystems reside on non flash based memory
    # zfs.trim.enable = true
  };

  swapDevices = [ ];

  boot.tmpOnTmpfs = true;


  nix.maxJobs = lib.mkDefault 8;
}
